const cotton = "/fabric-cotton.jpg";
const silk = "/fabric-silk.jpg";
const denim = "/fabric-denim.jpg";
const linen = "/fabric-linen.jpg";
const wool = "/fabric-wool.jpg";
const technical = "/fabric-technical.jpg";
const printed = "/fabric-printed.jpg";
import type {
  BuyerProfile,
  Category,
  Order,
  Product,
  SupplierProfile,
} from "@/types";

export const categories: Category[] = [
  {
    slug: "cotton",
    name: "Cotton",
    description: "Combed, organic and blended cotton for apparel and home textiles.",
    productCount: 4,
  },
  {
    slug: "silk",
    name: "Silk",
    description: "Mulberry, charmeuse and dupioni silks with premium hand feel.",
    productCount: 2,
  },
  {
    slug: "linen",
    name: "Linen",
    description: "European flax linens, undyed and garment-washed.",
    productCount: 2,
  },
  {
    slug: "denim",
    name: "Denim",
    description: "Selvedge, stretch and recycled denim in mill quantities.",
    productCount: 2,
  },
  {
    slug: "wool",
    name: "Wool & Suiting",
    description: "Merino, tweed and worsted suiting fabrics.",
    productCount: 2,
  },
  {
    slug: "technical",
    name: "Technical",
    description: "Performance knits, membranes and recycled polyester.",
    productCount: 2,
  },
];

export const fabricTypes = [
  "Organic Cotton",
  "Combed Cotton",
  "Mulberry Silk",
  "European Flax Linen",
  "Selvedge Denim",
  "Merino Wool",
  "Recycled Polyester",
  "Cotton Blend",
];

export const suppliers: SupplierProfile[] = [
  {
    id: "sup_1",
    businessName: "Meridian Mills",
    businessType: "Manufacturer",
    contactName: "Ayesha Rahman",
    email: "sales@meridianmills.com",
    phone: "+880 1711 220044",
    addressLine: "Plot 14, Export Processing Zone",
    city: "Chattogram",
    country: "Bangladesh",
    operatingHours: "Sun–Thu, 09:00 – 18:00",
    categories: ["Cotton", "Denim"],
    fabricTypes: ["Organic Cotton", "Combed Cotton", "Selvedge Denim"],
    moq: 300,
    about:
      "Vertically integrated mill producing knitted and woven cotton for global apparel brands since 1998.",
  },
  {
    id: "sup_2",
    businessName: "Atelier Soie",
    businessType: "Wholesaler",
    contactName: "Léa Fontaine",
    email: "orders@ateliersoie.fr",
    phone: "+33 4 78 22 11 09",
    addressLine: "22 Rue des Tisserands",
    city: "Lyon",
    country: "France",
    operatingHours: "Mon–Fri, 08:30 – 17:30",
    categories: ["Silk", "Wool & Suiting"],
    fabricTypes: ["Mulberry Silk", "Merino Wool"],
    moq: 120,
    about: "Fourth-generation silk house specialising in low-MOQ luxury fabrics.",
  },
  {
    id: "sup_3",
    businessName: "Northline Textiles",
    businessType: "Manufacturer",
    contactName: "Jonas Berg",
    email: "hello@northline.se",
    phone: "+46 8 559 22 10",
    addressLine: "Industrivägen 8",
    city: "Borås",
    country: "Sweden",
    operatingHours: "Mon–Fri, 07:00 – 16:00",
    categories: ["Technical", "Linen"],
    fabricTypes: ["Recycled Polyester", "European Flax Linen"],
    moq: 250,
    about: "Performance and sustainable fabrics with full traceability documentation.",
  },
];

export const currentSupplier = suppliers[0]!;

export const buyerProfile: BuyerProfile = {
  name: "Maya Chowdhury",
  company: "Kite & Loom Apparel",
  email: "maya@kiteandloom.com",
  phone: "+44 20 7946 1122",
  businessType: "Apparel Brand",
  industry: "Fashion & Apparel",
  interests: ["Cotton", "Linen", "Technical"],
  preferredFabrics: ["Organic Cotton", "European Flax Linen"],
  orderQuantity: "1,000 – 5,000 m",
  budgetRange: "₹8L – ₹40L per order",
};

export const products: Product[] = [
  {
    id: "prd_001",
    name: "Organic Combed Cotton Jersey 180 GSM",
    category: "Cotton",
    categorySlug: "cotton",
    fabricType: "Organic Cotton",
    description:
      "GOTS-certified single jersey knitted from long-staple combed cotton. Soft hand feel, low pilling and excellent dye uptake — built for premium tees and loungewear programmes.",
    colors: ["Ivory", "Sand", "Charcoal", "Sage"],
    specifications: [
      { label: "Weight", value: "180 GSM" },
      { label: "Width", value: "180 cm" },
      { label: "Composition", value: "100% Organic Cotton" },
      { label: "Certification", value: "GOTS 6.0" },
      { label: "Shrinkage", value: "< 3%" },
    ],
    stock: 8400,
    price: 4.2,
    moq: 500,
    isAvailable: true,
    image: cotton,
    gallery: [cotton, linen, printed],
    supplierId: "sup_1",
    supplierName: "Meridian Mills",
    leadTimeDays: 18,
    isFeatured: true,
  },
  {
    id: "prd_002",
    name: "Mulberry Silk Charmeuse 19 momme",
    category: "Silk",
    categorySlug: "silk",
    fabricType: "Mulberry Silk",
    description:
      "Grade 6A mulberry silk charmeuse with a fluid drape and mirror sheen. Ideal for evening wear, linings and premium scarves.",
    colors: ["Emerald", "Onyx", "Champagne"],
    specifications: [
      { label: "Weight", value: "19 momme" },
      { label: "Width", value: "140 cm" },
      { label: "Composition", value: "100% Mulberry Silk" },
      { label: "Finish", value: "Sand-washed" },
      { label: "Certification", value: "OEKO-TEX 100" },
    ],
    stock: 620,
    price: 21.5,
    moq: 120,
    isAvailable: true,
    image: silk,
    gallery: [silk, wool],
    supplierId: "sup_2",
    supplierName: "Atelier Soie",
    leadTimeDays: 24,
    isFeatured: true,
  },
  {
    id: "prd_003",
    name: "Raw Selvedge Denim 13.5 oz",
    category: "Denim",
    categorySlug: "denim",
    fabricType: "Selvedge Denim",
    description:
      "Shuttle-loomed indigo selvedge with a pronounced slub character that fades beautifully. Woven on vintage looms in limited weekly runs.",
    colors: ["Indigo", "Black Rinse"],
    specifications: [
      { label: "Weight", value: "13.5 oz" },
      { label: "Width", value: "76 cm" },
      { label: "Composition", value: "100% Cotton" },
      { label: "Loom", value: "Shuttle / selvedge" },
      { label: "Sanforized", value: "No" },
    ],
    stock: 1450,
    price: 12.8,
    moq: 300,
    isAvailable: true,
    image: denim,
    gallery: [denim, wool],
    supplierId: "sup_1",
    supplierName: "Meridian Mills",
    leadTimeDays: 21,
    isFeatured: true,
  },
  {
    id: "prd_004",
    name: "European Flax Linen 210 GSM",
    category: "Linen",
    categorySlug: "linen",
    fabricType: "European Flax Linen",
    description:
      "Undyed Normandy flax woven with a soft slub. Garment-washed for immediate softness with a naturally relaxed handle.",
    colors: ["Natural", "Oat", "Clay"],
    specifications: [
      { label: "Weight", value: "210 GSM" },
      { label: "Width", value: "150 cm" },
      { label: "Composition", value: "100% Linen" },
      { label: "Origin", value: "Normandy, France" },
      { label: "Finish", value: "Garment washed" },
    ],
    stock: 2600,
    price: 9.4,
    moq: 250,
    isAvailable: true,
    image: linen,
    gallery: [linen, cotton],
    supplierId: "sup_3",
    supplierName: "Northline Textiles",
    leadTimeDays: 16,
    isFeatured: true,
  },
  {
    id: "prd_005",
    name: "Merino Wool Suiting 260 GSM",
    category: "Wool & Suiting",
    categorySlug: "wool",
    fabricType: "Merino Wool",
    description:
      "Super 120s worsted merino with a fine herringbone. Crease-resistant and breathable for four-season tailoring.",
    colors: ["Charcoal", "Navy", "Stone"],
    specifications: [
      { label: "Weight", value: "260 GSM" },
      { label: "Width", value: "150 cm" },
      { label: "Composition", value: "100% Merino Wool" },
      { label: "Yarn", value: "Super 120s" },
      { label: "Weave", value: "Herringbone" },
    ],
    stock: 180,
    price: 27.9,
    moq: 100,
    isAvailable: true,
    image: wool,
    gallery: [wool, silk],
    supplierId: "sup_2",
    supplierName: "Atelier Soie",
    leadTimeDays: 28,
  },
  {
    id: "prd_006",
    name: "Recycled Performance Knit 145 GSM",
    category: "Technical",
    categorySlug: "technical",
    fabricType: "Recycled Polyester",
    description:
      "Four-way stretch interlock from post-consumer PET with moisture-wicking finish. Full traceability to bottle-flake input.",
    colors: ["Slate", "Black", "Fog"],
    specifications: [
      { label: "Weight", value: "145 GSM" },
      { label: "Width", value: "160 cm" },
      { label: "Composition", value: "88% rPET / 12% Elastane" },
      { label: "Stretch", value: "4-way" },
      { label: "Certification", value: "GRS" },
    ],
    stock: 5200,
    price: 6.75,
    moq: 400,
    isAvailable: true,
    image: technical,
    gallery: [technical, denim],
    supplierId: "sup_3",
    supplierName: "Northline Textiles",
    leadTimeDays: 14,
    isFeatured: true,
  },
  {
    id: "prd_007",
    name: "Hand Block Printed Cotton Poplin",
    category: "Cotton",
    categorySlug: "cotton",
    fabricType: "Combed Cotton",
    description:
      "Artisan block-printed poplin with azo-free pigment dyes. Each run carries small variations characteristic of hand printing.",
    colors: ["Terracotta", "Indigo", "Ochre"],
    specifications: [
      { label: "Weight", value: "120 GSM" },
      { label: "Width", value: "110 cm" },
      { label: "Composition", value: "100% Cotton" },
      { label: "Print", value: "Hand block, azo-free" },
      { label: "Repeat", value: "24 cm" },
    ],
    stock: 940,
    price: 7.1,
    moq: 200,
    isAvailable: true,
    image: printed,
    gallery: [printed, cotton],
    supplierId: "sup_1",
    supplierName: "Meridian Mills",
    leadTimeDays: 20,
  },
  {
    id: "prd_008",
    name: "Heavyweight Cotton Canvas 320 GSM",
    category: "Cotton",
    categorySlug: "cotton",
    fabricType: "Cotton Blend",
    description:
      "Dense plain-weave canvas for workwear, outerwear and bags. Enzyme-washed to remove stiffness without losing structure.",
    colors: ["Ecru", "Olive", "Black"],
    specifications: [
      { label: "Weight", value: "320 GSM" },
      { label: "Width", value: "155 cm" },
      { label: "Composition", value: "98% Cotton / 2% Elastane" },
      { label: "Finish", value: "Enzyme washed" },
      { label: "Tear strength", value: "High" },
    ],
    stock: 60,
    price: 8.9,
    moq: 300,
    isAvailable: true,
    image: cotton,
    gallery: [cotton, denim],
    supplierId: "sup_1",
    supplierName: "Meridian Mills",
    leadTimeDays: 22,
  },
  {
    id: "prd_009",
    name: "Stretch Denim 10 oz",
    category: "Denim",
    categorySlug: "denim",
    fabricType: "Cotton Blend",
    description:
      "Comfort stretch denim with strong recovery for high-volume jeans programmes. Consistent shade across large lots.",
    colors: ["Mid Blue", "Jet"],
    specifications: [
      { label: "Weight", value: "10 oz" },
      { label: "Width", value: "150 cm" },
      { label: "Composition", value: "92% Cotton / 6% Poly / 2% Elastane" },
      { label: "Recovery", value: "95%" },
      { label: "Sanforized", value: "Yes" },
    ],
    stock: 0,
    price: 6.4,
    moq: 500,
    isAvailable: false,
    image: denim,
    gallery: [denim],
    supplierId: "sup_1",
    supplierName: "Meridian Mills",
    leadTimeDays: 25,
  },
  {
    id: "prd_010",
    name: "Silk Dupioni Shantung",
    category: "Silk",
    categorySlug: "silk",
    fabricType: "Mulberry Silk",
    description:
      "Crisp dupioni with irregular slub and natural lustre for structured occasion wear and interiors.",
    colors: ["Champagne", "Ruby", "Forest"],
    specifications: [
      { label: "Weight", value: "80 GSM" },
      { label: "Width", value: "137 cm" },
      { label: "Composition", value: "100% Silk" },
      { label: "Hand", value: "Crisp" },
      { label: "Certification", value: "OEKO-TEX 100" },
    ],
    stock: 310,
    price: 17.2,
    moq: 120,
    isAvailable: true,
    image: silk,
    gallery: [silk, printed],
    supplierId: "sup_2",
    supplierName: "Atelier Soie",
    leadTimeDays: 26,
  },
  {
    id: "prd_011",
    name: "Washed Linen Blend Twill",
    category: "Linen",
    categorySlug: "linen",
    fabricType: "European Flax Linen",
    description:
      "Linen-cotton twill with a soft drape and reduced creasing — a practical alternative to pure linen for volume shirting.",
    colors: ["Oat", "Sage", "Slate"],
    specifications: [
      { label: "Weight", value: "190 GSM" },
      { label: "Width", value: "148 cm" },
      { label: "Composition", value: "55% Linen / 45% Cotton" },
      { label: "Finish", value: "Stone washed" },
      { label: "Shrinkage", value: "< 4%" },
    ],
    stock: 1750,
    price: 7.8,
    moq: 250,
    isAvailable: true,
    image: linen,
    gallery: [linen, technical],
    supplierId: "sup_3",
    supplierName: "Northline Textiles",
    leadTimeDays: 15,
  },
  {
    id: "prd_012",
    name: "Tweed Wool Blend 380 GSM",
    category: "Wool & Suiting",
    categorySlug: "wool",
    fabricType: "Merino Wool",
    description:
      "Mélange tweed with a dry hand and rich colour depth, woven for jackets and heritage outerwear.",
    colors: ["Moss", "Rust", "Graphite"],
    specifications: [
      { label: "Weight", value: "380 GSM" },
      { label: "Width", value: "150 cm" },
      { label: "Composition", value: "70% Wool / 30% Polyamide" },
      { label: "Weave", value: "Tweed" },
      { label: "Finish", value: "Milled" },
    ],
    stock: 45,
    price: 19.6,
    moq: 100,
    isAvailable: true,
    image: wool,
    gallery: [wool, cotton],
    supplierId: "sup_2",
    supplierName: "Atelier Soie",
    leadTimeDays: 30,
  },
];

export function getProduct(id: string) {
  return products.find((p) => p.id === id);
}

export function getSupplierProducts() {
  return products.filter((p) => p.supplierId === currentSupplier.id);
}

const shipping = {
  fullName: "Maya Chowdhury",
  company: "Kite & Loom Apparel",
  email: "maya@kiteandloom.com",
  phone: "+44 20 7946 1122",
  addressLine: "Unit 5, Ashfield Works, 14 Corbet Place",
  city: "London",
  state: "Greater London",
  postalCode: "E1 6NN",
  country: "United Kingdom",
};

function timeline(status: string, base: string) {
  const order = ["Pending", "Accepted", "Preparing", "Ready for Dispatch", "Completed"];
  const idx = order.indexOf(status);
  const day = new Date(base);
  return order.map((s, i) => ({
    status: s as Order["status"],
    at:
      i <= idx
        ? new Date(day.getTime() + i * 36 * 3600 * 1000).toISOString()
        : null,
  }));
}

export const orders: Order[] = [
  {
    id: "ord_1042",
    reference: "TX-1042",
    buyerName: "Maya Chowdhury",
    buyerCompany: "Kite & Loom Apparel",
    placedAt: "2026-07-28T09:20:00.000Z",
    status: "Preparing",
    items: [
      {
        productId: "prd_001",
        name: "Organic Combed Cotton Jersey 180 GSM",
        image: cotton,
        unitPrice: 4.2,
        quantity: 1200,
        supplierName: "Meridian Mills",
      },
      {
        productId: "prd_007",
        name: "Hand Block Printed Cotton Poplin",
        image: printed,
        unitPrice: 7.1,
        quantity: 400,
        supplierName: "Meridian Mills",
      },
    ],
    total: 1200 * 4.2 + 400 * 7.1,
    shipping,
    timeline: timeline("Preparing", "2026-07-28T09:20:00.000Z"),
  },
  {
    id: "ord_1039",
    reference: "TX-1039",
    buyerName: "Maya Chowdhury",
    buyerCompany: "Kite & Loom Apparel",
    placedAt: "2026-07-21T14:05:00.000Z",
    status: "Ready for Dispatch",
    items: [
      {
        productId: "prd_003",
        name: "Raw Selvedge Denim 13.5 oz",
        image: denim,
        unitPrice: 12.8,
        quantity: 600,
        supplierName: "Meridian Mills",
      },
    ],
    total: 600 * 12.8,
    shipping,
    timeline: timeline("Ready for Dispatch", "2026-07-21T14:05:00.000Z"),
  },
  {
    id: "ord_1031",
    reference: "TX-1031",
    buyerName: "Daniel Osei",
    buyerCompany: "Northgate Uniforms",
    placedAt: "2026-07-09T11:40:00.000Z",
    status: "Completed",
    items: [
      {
        productId: "prd_008",
        name: "Heavyweight Cotton Canvas 320 GSM",
        image: cotton,
        unitPrice: 8.9,
        quantity: 900,
        supplierName: "Meridian Mills",
      },
    ],
    total: 900 * 8.9,
    shipping: { ...shipping, fullName: "Daniel Osei", company: "Northgate Uniforms" },
    timeline: timeline("Completed", "2026-07-09T11:40:00.000Z"),
  },
  {
    id: "ord_1048",
    reference: "TX-1048",
    buyerName: "Sofia Marchetti",
    buyerCompany: "Casa Tessile",
    placedAt: "2026-08-01T08:15:00.000Z",
    status: "Pending",
    items: [
      {
        productId: "prd_001",
        name: "Organic Combed Cotton Jersey 180 GSM",
        image: cotton,
        unitPrice: 4.2,
        quantity: 800,
        supplierName: "Meridian Mills",
      },
    ],
    total: 800 * 4.2,
    shipping: { ...shipping, fullName: "Sofia Marchetti", company: "Casa Tessile", city: "Milan", country: "Italy" },
    timeline: timeline("Pending", "2026-08-01T08:15:00.000Z"),
  },
  {
    id: "ord_1046",
    reference: "TX-1046",
    buyerName: "Kenji Watanabe",
    buyerCompany: "Studio Ao",
    placedAt: "2026-07-31T16:45:00.000Z",
    status: "Accepted",
    items: [
      {
        productId: "prd_003",
        name: "Raw Selvedge Denim 13.5 oz",
        image: denim,
        unitPrice: 12.8,
        quantity: 350,
        supplierName: "Meridian Mills",
      },
      {
        productId: "prd_008",
        name: "Heavyweight Cotton Canvas 320 GSM",
        image: cotton,
        unitPrice: 8.9,
        quantity: 300,
        supplierName: "Meridian Mills",
      },
    ],
    total: 350 * 12.8 + 300 * 8.9,
    shipping: { ...shipping, fullName: "Kenji Watanabe", company: "Studio Ao", city: "Osaka", country: "Japan" },
    timeline: timeline("Accepted", "2026-07-31T16:45:00.000Z"),
  },
];

export const buyerOrders = orders.filter((o) => o.buyerCompany === "Kite & Loom Apparel");
